import { DownOutlined } from "@ant-design/icons";
import { MenuProps, message, Space } from "antd";
import { Layout as AntdLayout, Dropdown, Menu } from "antd";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";

import styles from "./index.module.css";
import Link from "next/link";

const { Header, Content, Sider } = AntdLayout;

const ITEMS = [
  {
    label: "TodoList",
    key: "todo",

    children: [
      { label: "TodoList", key: "/todolist" },
      { label: "Add", key: "/todolist/add" },
    ],
  },
  {
    label: "用户管理",
    key: "user",

    children: [
      { label: "用户列表", key: "/user" },
      { label: "用户添加", key: "/user/add" },
    ],
  },
];


export function Layout({ children }) {
  const router = useRouter();
  const activeMenu = router.pathname;
  const handleMenuClick = ({ key }) => {
    router.push(key);
  };

  let user = null;
  if (typeof window !== "undefined") {
    const userStorge = localStorage.getItem("user");
    if (userStorge) {
      user = JSON.parse(userStorge);
    }
  }
 
  const USER_ITEMS: MenuProps["items"] = [
    {
      label: <Link href="/user/edit/id">用户中心</Link>,
      key: "1",
    },
    {
      label: (
        <span
          onClick={async () => {
            message.success("登出成功");
            localStorage.removeItem("user");
            router.push("/login");
          }}
        >
          登出
        </span>
      ),
      key: "2",
    },
  ]

  return (
    <>
      <Head>
        <title>TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/myfavicon.ico" />
      </Head>
      <main className={styles.main}>
        <AntdLayout>
          <Header className={styles.header}>
            <Image
              src="/todolist.svg"
              width={30}
              height={30}
              alt="logo"
              className={styles.logo}
            />
            TodoList
            <span className={styles.user}>
              <Dropdown menu={{ items: USER_ITEMS }}>
                <a onClick={(e) => e.preventDefault()}>
                  <Space>
                    {user?.info?.nickName ? user?.info?.nickName : "未登录"}
                    <DownOutlined />
                  </Space>
                </a>
              </Dropdown>
            </span>
          </Header>
          <AntdLayout className={styles.sectionInner}>
            <Sider width={200}>
              <Menu
                mode="inline"
                defaultSelectedKeys={["/todolist"]}
                defaultOpenKeys={["todolist"]}
                selectedKeys={[activeMenu]}
                style={{ height: "100%", borderRight: 0 }}
                items={ITEMS}
                onClick={handleMenuClick}
              />
            </Sider>
            <AntdLayout className={styles.sectionContent}>
              <Content className={styles.content}>{children}</Content>
            </AntdLayout>
          </AntdLayout>
        </AntdLayout>
      </main>
    </>
  );
}
